Changes to enable JSON output | FIX for ISSUE_5
google/pullsheet pull request #40
Opened 2021-06-13 07:39 UTC by bharathk005

@tstromberg @cpanato 
I have added a new "out" flag
Usage: --out JSON or --out CSV
default: CSV

I have noticed that in cmd/review, cmd/prs, cmd/issues, cmd/issues-comments files, we are calling the Marshall function. So instead of redundantly checking for JSON/CSV output in each of these files, I have created a print package under pkg/print where we handle whether to print JSON/CSV. We can now call this function from all of those folders mentioned above. 

Example: 
go run pullsheet.go prs --repos kubernetes/minikube --since 2021-06-10 --out JSON --token-path <PathToMyToken> > prs.json

2021-06-17 13:51 UTC, bharathk005 commented
@cpanato @tstromberg I understand you must be busy. Can you please check this when you are available and provide feedback. Thanks.

2021-06-17 14:07 UTC, cpanato reviewed
I'm not a maintainer of this project but this change looks very nice! thanks for adding that

just gave some small nits

2021-06-17 14:07 UTC, cpanato commented on cmd/root.go
> +		"Output type - CSV/JSON",
maybe worth mention the CSV is the default option

2021-06-17 14:07 UTC, cpanato commented on cmd/root.go
> +		return fmt.Errorf("Invalid out parameter %s. Enter JSON/CSV", rootOpts.out)
```suggestion
		return fmt.Errorf("Invalid out parameter %s. Must be JSON or CSV", rootOpts.out)
```

just a suggestion

2021-06-17 14:07 UTC, cpanato commented on pkg/print/print.go
> +	var er error
usually we use `err` instead of `er` but this is a small nit

2021-06-17 14:07 UTC, cpanato commented on pkg/print/print.go
> +	var er error
can be 
```
var (
er error
out string
)
```

2021-06-17 14:11 UTC, cpanato commented
> @cpanato @tstromberg I understand you must be busy. Can you please check this when you are available and provide feedback. Thanks.

sorry for the delay to reply, thanks for this PR, looks cool

2021-06-17 14:39 UTC, bharathk005 commented
@cpanato Thanks for the quick response and suggestions. 
I have pushed a new commit based on your suggestions. Please review and provide feedback
Thanks for your time.

2021-06-28 05:53 UTC, bharathk005 commented
@cpanato I have pushed a new commit with the changes you mentioned. Please review and let me know. Also, please let me know whom I should contact to get this merged if everything looks okay

2021-06-28 06:55 UTC, cpanato commented
I'm not a maintainer of this project, but this change lgtm
thanks!

2021-06-28 09:16 UTC, bharathk005 commented
@tstromberg @MarlonGamez can you please review.

2021-06-28 20:15 UTC, MarlonGamez approved these changes
Nice change! Thanks for the contribution :) And sorry for the delay in review

2021-06-28 20:17 UTC, MarlonGamez requested changes
small changes requested by linter

2021-06-28 20:17 UTC, MarlonGamez commented on pkg/print/print.go
> +//This method prints the values in "data" interface to standatrd output in the format specified by "out_type", either JSON/CSV
```suggestion
// This method prints the values in "data" interface to standatrd output in the format specified by "out_type", either JSON/CSV
```

2021-06-28 20:17 UTC, MarlonGamez commented on pkg/print/print.go
> +func Print(data interface{}, out_type string) error {
```suggestion
func Print(data interface{}, outType string) error {
```

2021-06-28 20:17 UTC, MarlonGamez commented on cmd/root.go
> +		return fmt.Errorf("Invalid out parameter %s. Must be JSON or CSV", rootOpts.out)
```suggestion
		return fmt.Errorf("invalid out parameter %s. Must be JSON or CSV", rootOpts.out)
```

2021-07-02 13:32 UTC, bharathk005 commented
@MarlonGamez I have pushed a new commit based on the suggestions above. Please review and let me know.
Thanks for your time.

2021-07-07 23:16 UTC, merged

2021-07-07 23:16 UTC, MarlonGamez commented
hi @bharathk005 sorry for the delay, I was out a few days for a holiday. Thanks again for your contribution!